### ISSUE TITLE
Clarify use of reMarkable Cloud API

### ISSUE THREAD

**Issue by Braincoke** [khanhas/hackernews2remarkable#1]
I've only skimmed through your code but it looks like you don't rely on the reMarkable Cloud API, but I might be wrong.
I personally don't use the reMarkable Cloud and _love_ projects that don't rely on it.

It'd be great if you could add a note to clarify if you are using it or not, I'm sure a lot a future users passing through are asking themselves the same question.

**Comment by khanhas** [comment]
Oh thank you, I'm glad you like it!
My first attempt used rmAPI to push epub file to the cloud and then my device needs to download it. So I rewrote it recently and yeah, this project doesn't rely on `rmAPI` anymore. Yeah I will modify README page to clarify that.
Just reminder that it needs to be ran **on** device via `ssh` or any app launcher.
